[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "oi-zeigt"
version = "0.1.0"
description = "Tools to analyze the OI 63mu GREAT archive"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
license = {text = "MIT"}  # or your preferred license

dependencies = [
    "astropy",
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "click>=8.0",
    "tomli >= 1.1.0 ; python_version < '3.11'",
    "scikit-learn",
    # Add other dependencies as needed
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "flake8",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/yourusername/oi_zeigt"
Documentation = "https://oi-zeigt.readthedocs.io"

[tool.setuptools]
packages = ["oi_zeigt"]

[tool.setuptools.package-dir]
"" = "src"

# Command-line entry points
[project.scripts]
print_fits_info = "oi_zeigt.cli:print_fits_info"
plot_sample_spectra = "oi_zeigt.cli:plot_sample_spectra"
plot_sample_raw = "oi_zeigt.cli:plot_sample_raw"
plot_skies = "oi_zeigt.cli:plot_skies"
plot_skyobsfit = "oi_zeigt.cli:plot_skyobsfit"
pca_decompose = "oi_zeigt.pca_analysis.pca_decompose_per_mission:main_cli"
pca_correct = "oi_zeigt.pca_analysis.pca_correct_fits:main_correct_cli"
determine_pca_parameters = "oi_zeigt.pca_analysis.determine_pca_parameters:main_cli"
analyze_blanks = "oi_zeigt.cli:analyze_blanks"
filter_fits = "oi_zeigt.cli:filter_fits"
filter_missions = "oi_zeigt.cli:filter_missions"
apply_baseline = "oi_zeigt.cli:apply_baseline"
reduce_spectra = "oi_zeigt.cli:reduce_spectra_cmd"
average = "oi_zeigt.cli:average_cmd"
spechistogram = "oi_zeigt.cli:spechistogram_cmd"
rmsratio = "oi_zeigt.cli:rmsratio_cmd"
map_column = "oi_zeigt.cli:map_column_cmd"
map_integrated = "oi_zeigt.cli:map_integrated_cmd"
compare_map_integrated = "oi_zeigt.cli:compare_map_integrated_cmd"
create_datacube = "oi_zeigt.cli:create_datacube_cmd"
collapse_cube = "oi_zeigt.cli:collapse_cube_cmd"
compare_maps = "oi_zeigt.cli:compare_maps_cmd"
overlay_maps = "oi_zeigt.cli:overlay_maps_cmd"
split_fits = "oi_zeigt.cli:split_fits_cmd"
combine_fits = "oi_zeigt.cli:combine_fits"
cascade_plots = "oi_zeigt.cli:cascade_plots"
plot_spectra = "oi_zeigt.cli:plot_spectra_cmd"
plot_raw = "oi_zeigt.cli:plot_raw_cmd"
plot_shobs_window = "oi_zeigt.cli:plot_shobs_window_cmd"
prepare_for_pca = "oi_zeigt.cli:prepare_for_pca"
post_process_data = "oi_zeigt.cli:post_process_data_cmd"
examine_telluric = "oi_zeigt.cli:examine_telluric"
print_pca_parameters = "oi_zeigt.cli:print_pca_parameters"
